// outdoor-saas-fe/src/pages/BarrierGates.vue
<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-bold text-text-light dark:text-text-dark">道闸管理</h1>
      <button class="px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors">
        新增道闸
      </button>
    </div>

    <div v-if="loading" class="flex items-center justify-center h-64">
      <div class="text-subtext-light dark:text-subtext-dark">加载中...</div>
    </div>

    <div v-else-if="error" class="flex items-center justify-center h-64">
      <div class="text-red-500">{{ error }}</div>
    </div>

    <div v-else class="bg-surface-light dark:bg-surface-dark rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden">
      <table class="w-full">
        <thead class="bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">ID</th>
            <th class="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">道闸编号</th>
            <th class="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">设备编号</th>
            <th class="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">门岗位置</th>
            <th class="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">操作</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr
            v-for="gate in barrierGates"
            :key="gate.id"
            class="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors cursor-pointer"
            @click="$router.push(`/barrier-gates/${gate.id}`)"
          >
            <td class="px-6 py-4 whitespace-nowrap text-sm text-text-light dark:text-text-dark">{{ gate.id }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-text-light dark:text-text-dark">{{ gate.gateNo }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-subtext-light dark:text-subtext-dark">{{ gate.deviceNo }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-subtext-light dark:text-subtext-dark">{{ gate.doorLocation }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm space-x-2" @click.stop>
              <button
                class="text-primary hover:text-primary/80 transition-colors"
                @click="$router.push(`/barrier-gates/${gate.id}`)"
              >
                查看
              </button>
              <button class="text-primary hover:text-primary/80 transition-colors">编辑</button>
              <button class="text-red-500 hover:text-red-600 transition-colors">删除</button>
            </td>
          </tr>
        </tbody>
      </table>

      <Pagination
        :current="currentPage"
        :page-size="pageSize"
        :total="total"
        @change="setPage"
        @page-size-change="setPageSize"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { barrierGateService } from '@/src/services/barrierGateService';
import type { BarrierGate } from '@/src/services/barrierGateService';
import type { BarrierGateQueryParam } from '@/src/types/query';
import Pagination from '@/src/components/Pagination.vue';
import { usePagination } from '@/src/composables/usePagination';

const {
  data: barrierGates,
  loading,
  error,
  currentPage,
  pageSize,
  total,
  setPage,
  setPageSize,
} = usePagination<BarrierGate, BarrierGateQueryParam>({
  fetchFn: barrierGateService.filterPage,
  defaultPageSize: 10,
});
</script>

// outdoor-saas-fe/src/pages/BarrierGates.tsx
import { useNavigate } from 'react-router-dom';
import { barrierGateService } from '../services/barrierGateService';
import type { BarrierGate } from '../services/barrierGateService';
import type { BarrierGateQueryParam } from '../types/query';
import Pagination from '../components/Pagination';
import { usePagination } from '../hooks/usePagination';

export default function BarrierGates() {
  const navigate = useNavigate();
  const {
    data: barrierGates,
    loading,
    error,
    currentPage,
    pageSize,
    total,
    setPage,
    setPageSize,
  } = usePagination<BarrierGate, BarrierGateQueryParam>({
    fetchFn: barrierGateService.filterPage,
    defaultPageSize: 10,
  });

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-subtext-light dark:text-subtext-dark">加载中...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-red-500">{error}</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-text-light dark:text-text-dark">道闸管理</h1>
        <button className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors">
          新增道闸
        </button>
      </div>

      <div className="bg-surface-light dark:bg-surface-dark rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden">
        <table className="w-full">
          <thead className="bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">ID</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">道闸编号</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">设备编号</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">门岗位置</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-subtext-light dark:text-subtext-dark uppercase tracking-wider">操作</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
            {barrierGates.map((gate) => (
              <tr
                key={gate.id}
                className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors cursor-pointer"
                onClick={() => navigate(`/barrier-gates/${gate.id}`)}
              >
                <td className="px-6 py-4 whitespace-nowrap text-sm text-text-light dark:text-text-dark">{gate.id}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-text-light dark:text-text-dark">{gate.gateNo}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-subtext-light dark:text-subtext-dark">{gate.deviceNo}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-subtext-light dark:text-subtext-dark">{gate.doorLocation}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm space-x-2" onClick={(e) => e.stopPropagation()}>
                  <button
                    className="text-primary hover:text-primary/80 transition-colors"
                    onClick={() => navigate(`/barrier-gates/${gate.id}`)}
                  >
                    查看
                  </button>
                  <button className="text-primary hover:text-primary/80 transition-colors">编辑</button>
                  <button className="text-red-500 hover:text-red-600 transition-colors">删除</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* 分页组件 */}
        <Pagination
          current={currentPage}
          pageSize={pageSize}
          total={total}
          onChange={setPage}
          onPageSizeChange={setPageSize}
        />
      </div>
    </div>
  );
}
